import {
  FaArrowRotateLeft,
  FaArrowRotateRight,
  FaBezierCurve,
  FaBookOpen,
  FaCircleInfo,
  FaDownload,
  FaDrawPolygon,
  FaGear,
  FaLink,
  FaMagnet,
  FaPencil,
  FaPaintbrush,
  FaRegCircle,
  FaRegHand,
  FaRegSquare,
  FaTableCells,
  FaTableColumns,
  FaTerminal,
  FaTrash,
  FaUpload,
} from 'react-icons/fa6';
import type { ActionDef } from './types';
import { getWorkspaceViewDefs } from '@/core/workspaceViews';

export const BASE_ACTION_DEFS: ActionDef[] = [
  {
    id: 'importApollo',
    label: 'Import Apollo Map...',
    category: 'file',
    icon: FaUpload,
    inCommandPalette: true,
    menu: 'File',
    menuOrder: 1,
  },
  {
    id: 'exportApolloBin',
    label: 'Export Apollo Map (.bin)',
    category: 'file',
    shortcut: '⌘S',
    keybinding: { key: 's', ctrl: true, global: true },
    icon: FaDownload,
    inCommandPalette: true,
    menu: 'File',
    menuOrder: 11,
  },
  {
    id: 'exportApolloText',
    label: 'Export Apollo Map (.txt)',
    category: 'file',
    shortcut: '⇧⌘S',
    keybinding: { key: 's', ctrl: true, shift: true, global: true },
    icon: FaDownload,
    inCommandPalette: true,
    menu: 'File',
    menuOrder: 12,
  },
  {
    id: 'settings',
    label: 'Settings',
    category: 'file',
    shortcut: '⌘,',
    keybinding: { key: ',', ctrl: true },
    icon: FaGear,
    inCommandPalette: true,
    menu: 'File',
    menuOrder: 90,
  },
  {
    id: 'undo',
    label: 'Undo',
    category: 'edit',
    shortcut: '⌘Z',
    keybinding: { key: 'z', ctrl: true, global: true },
    icon: FaArrowRotateLeft,
    inCommandPalette: true,
    menu: 'Edit',
    menuOrder: 10,
  },
  {
    id: 'redo',
    label: 'Redo',
    category: 'edit',
    shortcut: '⇧⌘Z',
    keybinding: { key: 'z', ctrl: true, shift: true, global: true },
    icon: FaArrowRotateRight,
    inCommandPalette: true,
    menu: 'Edit',
    menuOrder: 20,
  },
  {
    id: 'delete',
    label: 'Delete Selection',
    category: 'edit',
    shortcut: '⌫',
    keybinding: { key: 'delete' },
    icon: FaTrash,
    inCommandPalette: true,
    menu: 'Edit',
    menuOrder: 40,
  },
  {
    id: 'toggleGrid',
    label: 'Toggle Grid',
    category: 'view',
    shortcut: '⌘G',
    keybinding: { key: 'g', ctrl: true, global: true },
    icon: FaTableCells,
    inCommandPalette: true,
    menu: 'View',
    menuOrder: 40,
    isToggle: true,
    uiSlot: 'view',
    uiOrder: 10,
  },
  {
    id: 'toggleSnap',
    label: 'Toggle Snap',
    category: 'view',
    icon: FaMagnet,
    inCommandPalette: true,
    menu: 'View',
    menuOrder: 41,
    isToggle: true,
    uiSlot: 'view',
    uiOrder: 20,
  },
  {
    id: 'resetLayout',
    label: 'Reset Layout',
    category: 'view',
    icon: FaTableColumns,
    inCommandPalette: true,
    menu: 'View',
    menuOrder: 10,
  },
  {
    id: 'commandPalette',
    label: 'Command Palette',
    category: 'view',
    shortcut: '⌘K',
    keybinding: { key: 'k', ctrl: true, global: true },
    icon: FaTerminal,
    inCommandPalette: false,
  },
  {
    id: 'about',
    label: 'Version Information',
    category: 'help',
    icon: FaCircleInfo,
    inCommandPalette: true,
    menu: 'About',
    menuOrder: 10,
  },
  {
    id: 'openHelp',
    label: 'Help Documentation',
    category: 'help',
    icon: FaBookOpen,
    inCommandPalette: true,
    menu: 'About',
    menuOrder: 20,
  },
  {
    id: 'defaultMode',
    label: 'Default (Pan)',
    category: 'selection',
    shortcut: 'H',
    keybinding: { key: 'h' },
    icon: FaRegHand,
    inCommandPalette: true,
    isToggle: true,
  },
  {
    id: 'connectLanes',
    label: 'Connect Lanes',
    category: 'edit',
    shortcut: 'C',
    keybinding: { key: 'c' },
    icon: FaLink,
    inCommandPalette: true,
    menu: 'Edit',
    menuOrder: 50,
    isToggle: true,
  },
  {
    id: 'boundaryBrush',
    label: 'Boundary Brush',
    category: 'edit',
    shortcut: 'V',
    keybinding: { key: 'v' },
    icon: FaPaintbrush,
    inCommandPalette: true,
    menu: 'Edit',
    menuOrder: 55,
    isToggle: true,
  },
  {
    id: 'tool:drawPolyline',
    label: 'Draw Polyline',
    category: 'tool',
    shortcut: 'P',
    keybinding: { key: 'p' },
    icon: FaPencil,
    inCommandPalette: true,
    drawTool: 'drawPolyline',
  },
  {
    id: 'tool:drawBezier',
    label: 'Draw Bezier',
    category: 'tool',
    shortcut: 'B',
    keybinding: { key: 'b' },
    icon: FaBezierCurve,
    inCommandPalette: true,
    drawTool: 'drawBezier',
  },
  {
    id: 'tool:drawArc',
    label: 'Draw Arc',
    category: 'tool',
    shortcut: 'A',
    keybinding: { key: 'a' },
    icon: FaRegCircle,
    inCommandPalette: true,
    drawTool: 'drawArc',
  },
  {
    id: 'tool:drawRotatedRect',
    label: 'Draw Rectangle',
    category: 'tool',
    shortcut: 'R',
    keybinding: { key: 'r' },
    icon: FaRegSquare,
    inCommandPalette: true,
    drawTool: 'drawRotatedRect',
  },
  {
    id: 'tool:drawPolygon',
    label: 'Draw Polygon',
    category: 'tool',
    shortcut: 'G',
    keybinding: { key: 'g' },
    icon: FaDrawPolygon,
    inCommandPalette: true,
    drawTool: 'drawPolygon',
  },
  {
    id: 'tool:drawCatmullRom',
    label: 'Draw CatmullRom',
    category: 'tool',
    icon: FaBezierCurve,
    inCommandPalette: true,
    drawTool: 'drawCatmullRom',
  },
];

export function getWorkspaceViewActionDefs(): ActionDef[] {
  return getWorkspaceViewDefs().map((view) => ({
    id: view.actionId,
    label: view.label,
    category: 'view',
    icon: view.icon,
    inCommandPalette: true,
    menu: 'View',
    menuOrder: view.menuOrder,
    isToggle: true,
  }));
}

export function getActionDefs(): ActionDef[] {
  const workspaceViewActions = getWorkspaceViewActionDefs();
  const insertAt = BASE_ACTION_DEFS.findIndex((action) => action.id === 'commandPalette');
  if (insertAt < 0) return [...BASE_ACTION_DEFS, ...workspaceViewActions];
  return [
    ...BASE_ACTION_DEFS.slice(0, insertAt),
    ...workspaceViewActions,
    ...BASE_ACTION_DEFS.slice(insertAt),
  ];
}
