import { defineConfig } from 'vitepress';
import { version } from '../../package.json';

// VITEPRESS_BASE is injected by GitHub Actions for sub-path deployment
// e.g. /apollo-map-studio/ when hosted at github.io/<repo>/
const base = process.env.VITEPRESS_BASE ?? '/';

export default defineConfig({
  title: 'Apollo Map Studio',
  description: 'Desktop and web HD map editor for the Apollo autonomous driving platform',
  base,

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Architecture', link: '/architecture/overview' },
      { text: 'API', link: '/api/' },
      {
        text: 'More',
        items: [
          { text: 'Reference', link: '/reference/' },
          { text: 'Recipes', link: '/recipes/adding-a-new-action' },
          { text: 'Contributing', link: '/contributing/development-setup' },
        ],
      },
      {
        text: `v${version}`,
        items: [{ text: 'Changelog', link: '/changelog' }],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Import', link: '/guide/import' },
            { text: 'Importing Deep Dive', link: '/guide/importing' },
            { text: 'Coordinate System', link: '/guide/coordinate-system' },
            { text: 'Drawing Tools', link: '/guide/drawing-tools' },
            { text: 'Drawing Lanes', link: '/guide/drawing-lanes' },
            { text: 'Editing & Snapping', link: '/guide/editing-and-snapping' },
            { text: 'Topology & Connections', link: '/guide/topology' },
            { text: 'Topology & Junctions', link: '/guide/topology-and-junctions' },
            { text: 'Map Elements', link: '/guide/map-elements' },
            { text: 'Layer Tree', link: '/guide/layer-tree' },
            { text: 'Inspector', link: '/guide/inspector' },
            { text: 'Export', link: '/guide/export' },
            { text: 'Exporting Deep Dive', link: '/guide/exporting' },
            { text: 'License Activation', link: '/guide/license-activation' },
            { text: 'MenuBar & ToolStrip', link: '/guide/menubar-and-toolstrip' },
            { text: 'Activity Bar & Panels', link: '/guide/activity-bar-and-panels' },
            { text: 'Command Palette', link: '/guide/command-palette' },
            { text: 'Settings', link: '/guide/settings' },
            { text: 'Keyboard Shortcuts', link: '/guide/shortcuts' },
            { text: 'Shortcut Alias', link: '/guide/keyboard-shortcuts' },
            { text: 'Troubleshooting', link: '/guide/troubleshooting' },
          ],
        },
      ],
      '/architecture/': [
        {
          text: 'Architecture',
          items: [
            { text: 'Overview', link: '/architecture/overview' },
            { text: 'Tech Stack', link: '/architecture/tech-stack' },
            { text: 'Layered Architecture', link: '/architecture/layered-architecture' },
            { text: 'Workspace Layout', link: '/architecture/workspace-layout' },
            { text: 'State Management', link: '/architecture/state-management' },
            { text: 'Action Registry', link: '/architecture/action-registry' },
            { text: 'Rendering Pipeline', link: '/architecture/rendering' },
            { text: 'Rendering Pipeline Deep Dive', link: '/architecture/rendering-pipeline' },
            { text: 'Cold / Hot Layers', link: '/architecture/cold-hot-layers' },
            { text: 'Geometry Engine', link: '/architecture/geometry-engine' },
            { text: 'Coordinate System', link: '/architecture/coordinate-system' },
            { text: 'Spatial Index', link: '/architecture/spatial-index' },
            { text: 'Map Event Router', link: '/architecture/map-event-router' },
            { text: 'FSM Design', link: '/architecture/fsm-design' },
            { text: 'Junction Graph', link: '/architecture/junction-graph' },
            { text: 'Junction Stitching', link: '/architecture/junction-stitching' },
            { text: 'Overlap Derivation', link: '/architecture/overlap-derivation' },
            { text: 'Inspector System', link: '/architecture/inspector-system' },
            { text: 'Inspector Schema', link: '/architecture/inspector-schema' },
            { text: 'Derive Engine', link: '/architecture/derive-engine' },
            { text: 'Anti-Corruption Layer', link: '/architecture/anti-corruption-layer' },
            { text: 'entityOps', link: '/architecture/entityops' },
            { text: 'Worker Protocol', link: '/architecture/worker-protocol' },
            { text: 'Export Engine', link: '/architecture/export-engine' },
            { text: 'Electron Integration', link: '/architecture/electron-integration' },
            { text: 'License System', link: '/architecture/license-system' },
            { text: 'Design Tokens', link: '/architecture/design-tokens' },
            { text: 'Testing Strategy', link: '/architecture/testing-strategy' },
            { text: 'Build & Bundle', link: '/architecture/build-and-bundle' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'Top-Level API',
          items: [
            { text: 'API Overview', link: '/api/' },
            { text: 'store/mapStore', link: '/api/store-map' },
            { text: 'store/uiStore', link: '/api/store-ui' },
            { text: 'geo/projection', link: '/api/geo-projection' },
            { text: 'geo/laneGeometry', link: '/api/geo-lane-geometry' },
            { text: 'geo/overlapCalc', link: '/api/geo-overlap-calc' },
            { text: 'proto/loader', link: '/api/proto-loader' },
            { text: 'proto/codec', link: '/api/proto-codec' },
            { text: 'proto/schema', link: '/api/proto-schema' },
            { text: 'export/buildBaseMap', link: '/api/export-base-map' },
            { text: 'export/buildSimMap', link: '/api/export-sim-map' },
            { text: 'export/buildRoutingMap', link: '/api/export-routing-map' },
            { text: 'import/parseBaseMap', link: '/api/import-parse-base-map' },
          ],
        },
        {
          text: 'Components',
          collapsed: true,
          items: [
            { text: 'Components Overview', link: '/api/components/' },
            { text: 'WorkspaceLayout', link: '/api/components/workspace-layout' },
            { text: 'MapCanvas', link: '/api/components/map-canvas' },
            { text: 'MenuBar', link: '/api/components/menu-bar' },
            { text: 'ToolStrip', link: '/api/components/tool-strip' },
            { text: 'ActivityBar', link: '/api/components/activity-bar' },
            { text: 'MapOutline', link: '/api/components/map-outline' },
            { text: 'LayerTree', link: '/api/components/layer-tree' },
            { text: 'SearchPanel', link: '/api/components/search-panel' },
            { text: 'InspectorForms', link: '/api/components/inspector-forms' },
            { text: 'LaneRefList', link: '/api/components/lane-ref-list' },
            { text: 'SettingsPanel', link: '/api/components/settings-panel' },
            { text: 'StatusBar', link: '/api/components/status-bar' },
            { text: 'TimelinePanel', link: '/api/components/timeline-panel' },
            { text: 'CommandPalette', link: '/api/components/command-palette' },
            { text: 'TaskProgressOverlay', link: '/api/components/task-progress-overlay' },
            { text: 'ProjPickerDialog', link: '/api/components/proj-picker-dialog' },
            { text: 'LicenseBanner', link: '/api/components/license-banner' },
            { text: 'ActivationDialog', link: '/api/components/activation-dialog' },
          ],
        },
        {
          text: 'Hooks',
          collapsed: true,
          items: [
            { text: 'Hooks Overview', link: '/api/hooks' },
            { text: 'useActionDispatcher', link: '/api/hooks/use-action-dispatcher' },
            { text: 'useApolloLayer', link: '/api/hooks/use-apollo-layer' },
            { text: 'useColdLayer', link: '/api/hooks/use-cold-layer' },
            { text: 'useHotLayer', link: '/api/hooks/use-hot-layer' },
            { text: 'useOverlayLayer', link: '/api/hooks/use-overlay-layer' },
            { text: 'useGridLayer', link: '/api/hooks/use-grid-layer' },
            { text: 'useMapLibreInit', link: '/api/hooks/use-map-libre-init' },
            { text: 'useMapEventRouter', link: '/api/hooks/use-map-event-router' },
            { text: 'Map Event Router Internals', link: '/api/hooks/map-event-router-internals' },
            { text: 'useDrawCommit', link: '/api/hooks/use-draw-commit' },
            { text: 'useCursorManager', link: '/api/hooks/use-cursor-manager' },
            { text: 'useDragPan', link: '/api/hooks/use-drag-pan' },
            { text: 'useLicense', link: '/api/hooks/use-license' },
          ],
        },
        {
          text: 'Core',
          collapsed: true,
          items: [
            { text: 'Core Overview', link: '/api/core/' },
            { text: 'Actions Registry', link: '/api/core/actions-registry' },
            { text: 'editorMachine', link: '/api/core/fsm-editor-machine' },
            { text: 'Elements', link: '/api/core/elements' },
            { text: 'Elements Derive', link: '/api/core/elements-derive' },
            { text: 'Elements Overlap', link: '/api/core/elements-overlap' },
            { text: 'Geometry Apollo Compile', link: '/api/core/geometry-apollo-compile' },
            { text: 'Geometry Connect Lanes', link: '/api/core/geometry-connect-lanes' },
            { text: 'Geometry Lane Topology', link: '/api/core/geometry-lane-topology' },
            { text: 'Geometry Interpolate', link: '/api/core/geometry-interpolate' },
            { text: 'Geometry Snap', link: '/api/core/geometry-snap' },
            { text: 'Geometry Validation', link: '/api/core/geometry-validation' },
            { text: 'Geometry Hit Test', link: '/api/core/geometry-hit-test' },
            { text: 'Geometry Lane Junctions', link: '/api/core/geometry-lane-junctions' },
            { text: 'Spatial Worker', link: '/api/core/workers-spatial' },
            { text: 'Overlap Worker', link: '/api/core/workers-overlap' },
            { text: 'Worker Protocol', link: '/api/core/workers-protocol' },
            { text: 'Junction Graph Worker', link: '/api/core/workers-junction-graph' },
          ],
        },
        {
          text: 'IO',
          collapsed: true,
          items: [
            { text: 'Map IO', link: '/api/io/map-io' },
            { text: 'Apollo IO Bridge', link: '/api/io/apollo-io-bridge' },
            { text: 'Apollo IO Protocol', link: '/api/io/apollo-io-protocol' },
            { text: 'File IO', link: '/api/io/file-io' },
            { text: 'Proto Loader', link: '/api/io/proto-loader' },
            { text: 'Proto Bin Codec', link: '/api/io/proto-codec-bin' },
            { text: 'Proto Text Codec', link: '/api/io/proto-codec-text' },
            { text: 'Proto Adapter', link: '/api/io/proto-adapter' },
            { text: 'Proto Projection', link: '/api/io/proto-projection' },
            { text: 'Proto Entity Bridge', link: '/api/io/proto-entity-bridge' },
            { text: 'Proto Apollo GeoJSON', link: '/api/io/proto-apollo-geojson' },
            { text: 'Proto Editor Meta', link: '/api/io/proto-editor-meta' },
          ],
        },
        {
          text: 'Stores, Lib, Types, Electron',
          collapsed: true,
          items: [
            { text: 'Apollo Map Store', link: '/api/store/apollo-map-store' },
            { text: 'License Store', link: '/api/store/license-store' },
            { text: 'Settings Store', link: '/api/store/settings-store' },
            { text: 'Task Progress Store', link: '/api/store/task-progress-store' },
            { text: 'Proj Dialog Store', link: '/api/store/proj-dialog-store' },
            { text: 'lib/entityOps', link: '/api/lib/entity-ops' },
            { text: 'lib/editableGuard', link: '/api/lib/editable-guard' },
            { text: 'lib/enumLabels', link: '/api/lib/enum-labels' },
            { text: 'lib/geo', link: '/api/lib/geo' },
            { text: 'lib/geoJsonHelpers', link: '/api/lib/geo-json-helpers' },
            { text: 'lib/idGenerator', link: '/api/lib/id-generator' },
            { text: 'lib/licenseBridge', link: '/api/lib/license-bridge' },
            { text: 'lib/mapIcons', link: '/api/lib/map-icons' },
            { text: 'types/apollo', link: '/api/types/apollo' },
            { text: 'types/entities', link: '/api/types/entities' },
            { text: 'types/editor', link: '/api/types/editor' },
            { text: 'types/inspectorSchema', link: '/api/types/inspector-schema' },
            { text: 'Electron', link: '/api/electron' },
            { text: 'Electron Main Process', link: '/api/electron/main-process' },
            { text: 'Electron Preload', link: '/api/electron/preload' },
            { text: 'Electron License Manager', link: '/api/electron/license-manager' },
          ],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Reference Overview', link: '/reference/' },
            { text: 'Proto Schema', link: '/reference/proto-schema' },
            { text: 'Apollo Types', link: '/reference/apollo-types' },
            { text: 'Enum Mappings', link: '/reference/enum-mappings' },
            { text: 'Benchmark Budgets', link: '/reference/benchmark-budgets' },
            { text: 'CI Pipeline', link: '/reference/ci-pipeline' },
            { text: 'Color Palette', link: '/reference/color-palette' },
            { text: 'Design Tokens', link: '/reference/design-tokens' },
            { text: 'Glossary', link: '/reference/glossary' },
          ],
        },
      ],
      '/recipes/': [
        {
          text: 'Recipes',
          items: [
            { text: 'Adding a New Action', link: '/recipes/adding-a-new-action' },
            { text: 'Adding a New Drawing Tool', link: '/recipes/adding-a-new-drawing-tool' },
            { text: 'Adding a New Element', link: '/recipes/adding-a-new-element' },
            { text: 'Adding a Worker', link: '/recipes/adding-a-worker' },
            { text: 'Customizing Shortcuts', link: '/recipes/customizing-shortcuts' },
            { text: 'Debugging Map Pipeline', link: '/recipes/debugging-the-map-pipeline' },
            { text: 'Extending the Inspector', link: '/recipes/extending-the-inspector' },
            { text: 'Issuing License Keys', link: '/recipes/issuing-license-keys' },
            { text: 'Packaging Desktop Builds', link: '/recipes/packaging-desktop-builds' },
            { text: 'Theming with AMS Tokens', link: '/recipes/theming-with-ams-tokens' },
          ],
        },
      ],
      '/contributing/': [
        {
          text: 'Contributing',
          items: [
            { text: 'Development Setup', link: '/contributing/development-setup' },
            { text: 'Code Style', link: '/contributing/code-style' },
            { text: 'Commit Conventions', link: '/contributing/commit-conventions' },
            { text: 'PR Checklist', link: '/contributing/pr-checklist' },
            { text: 'Testing', link: '/contributing/testing' },
            { text: 'Benchmarking', link: '/contributing/benchmarking' },
            { text: 'Release Process', link: '/contributing/release-process' },
          ],
        },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/SakuraPuare/apollo-map-studio' }],

    footer: {
      message: 'Released under the CC BY-NC 4.0 License.',
      copyright: 'ShuYingJiYu',
    },

    search: {
      provider: 'local',
    },
  },
});
